#!/bin/bash
set -euxo pipefail
cd "$(dirname $BASH_SOURCE)"
source _common.source

DOCKER_COMMAND="${DOCKER_COMMAND:-docker}"

$DOCKER_COMMAND build \
    --build-arg SYNAPSE_VERSION="${SYNAPSE_VERSION}" \
    -t "${IMAGE_REPO}:${IMAGE_TAG}" \
    ..
